$modelname "C:\Work\HL\sc_towerdefense2\conveyorbelt\conveyorbelt.mdl"
$cd "\Work\HL\sc_towerdefense2\conveyorbelt\"
$cdtexture "\Work\HL\sc_towerdefense2\conveyorbelt\"
$cliptotextures

$scale 1.0

$origin 0 0 0 90 0 0

$bodygroup body
{
studio "./conveyorbelt00"
studio "./conveyorbelt01"
studio "./conveyorbelt02"
studio "./conveyorbelt03"
studio "./conveyorbelt04"
studio "./conveyorbelt05"
studio "./conveyorbelt06"
studio "./conveyorbelt07"
studio "./conveyorbelt08"
studio "./conveyorbelt09"
}

$sequence idle1 "idle1" loop fps 30 ACT_IDLE 1
